# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: To Chin Yu | SLAC | Stanford | SuperCDMS
description: >- # this means to ignore newlines until "baseurl:"
  Personal site of To Chin Yu
#baseurl: "/" # the subpath of the site
url: "https://obeliskalpha.com" # the base hostname & protocol for the site
#og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: ytc@stanford.edu
      link: mailto:ytc@stanford.edu

  follow:
    - name: Twitter
      link: http://twitter.com/ytcsss
      username: "@ytcsss"
    - name: LinkedIn
      link: http://linkedin.com/in/to-chin-yu-281a05136
    - name: GitHub
      link: http://github.com/ytcs
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
  - jekyll-spaceship

disqus:
  shortname:  obeliskalpha

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
