# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: To Chin Yu
description: Personal site of To Chin Yu
url: "https://ytcs.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Kramdown settings for better math support
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

# MathJax settings
mathjax: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/

# Author information
author:
  name: To Chin Yu
  email: public@tochinyu.com

footer:
  show_powered_by: false
  contact:

  follow:
    - name: Email
      link: mailto:public@tochinyu.com
    - name: LinkedIn
      link: http://linkedin.com/in/to-chin-yu-281a05136
    - name: GitHub
      link: http://github.com/ytcs
    - name: RSS
      link: /feed.xml

# Used for defeating caching
version: 1
